name: Upload to S3 Use oidc

on:
  push:
    branches:
      - master
    paths:
      - "index.html"

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: test-bucket-leedonggyu-10

permissions:
  id-token: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp index.html s3://${{ env.S3_BUCKET }}/index.html
